name: Docker Elastic Beanstalk Deployment

on:
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t mk671326/docker-react -f Dockerfile.dev .

    - name: Run Test Coverage
      run: docker run -e CI=true mk671326/docker-react npm run test -- --coverage

    - name: Dockerhub Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Container Publish
      run: docker push mk671326/docker-react		
  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Zip deployment package
      run: zip -r deployment-package.zip ./*
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v17
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: "docker-react"
        environment_name: "Docker-react-env"
        region: "us-east-1"
        version_label: "Sample"
        deployment_package: "deployment-package.zip"
