name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t mk67132/docker-react -f Dockerfile.dev .
    - name: Running Test Coverage
      run: docker run -e CI=true mk67132/docker-react npm run test -- --coverage
